### ISSUE TITLE
When we press on an open card, close it and move to the next card

### ISSUE THREAD

**Issue by benraziel** [benraziel/hs-recall#11]
this will make navigation between cards easier - no need to move the mouse towards the arrow, just keep tapping on the cards to advance..

**Comment by benraziel** [comment]
on second thought, not sure we want this kind of "automatic" behavior.
maybe moving the next/prev arrow keys closer to the cards will solve the issue

**Comment by guyius** [comment]
agreeing with your second comment this will feel akward if you'll automatically move a card
