### ISSUE TITLE
Change checkboxes to combo-boxes

### ISSUE THREAD

**Issue by benraziel** [benraziel/hs-recall#12]
Curently,l filtering cards of one specific class is very annoying (need to uncheck 8 checkboxes).
I think combo boxes will work much better, and won't hurt functionality (i.e usually you want to filter by only one type, not by many)

**Comment by guyius** [comment]
so you want to be able to choose between one or all? 
what do you think we should have 10 buttons, 1 per class and an all button that will be selected on first load.

**Comment by benraziel** [comment]
I don't see a scenario where a user would want to "learn all the mage or rogue cards". I think the common scenario would be "I want to learn all the mage cards", or "I want to learn all the mage spells". Using combo boxes will let you do that and keep the UI simple
